theme: jekyll-theme-time-machine
title: Kenneth Miller's ePortfolio
description: This webiste is used to showcase my various skills in the world of technology. From C++ to Javascript and algorithms to databses, I pride myself on knowing as much as possilbe about the technology that is currently being used in all facets of the IT world.
